insert into public.projects (name, scope, location, status, completion, description, featured, category, sort_order)
values
  ('Sunberry Homes 1 Subdivision', 'Project Management', 'Soong, Mactan, Lapu-Lapu City', 'Completed', '2022', null, false, null, 0),
  ('Sunberry Homes 2 Subdivision', 'Project Management', 'Sudtonggan, Basak, Lapu-Lapu City', 'Completed', '2022', null, false, null, 1),
  ('Toledo Medical Clinic', 'Project Consultant', 'Bonifacio District, Panagdait, Mabolo, Cebu City', 'Completed', '2021', null, false, null, 2),
  ('Dorothea Commercial Shop', 'General Contractor (All-in works)', 'Pusok, Lapu-Lapu City', 'Completed', '2020', null, false, null, 3),
  ('Ceburrific Pasalubong Shop', 'General Contractor (All-in works)', 'Mactan Cebu International Airport', 'Completed', '2020', null, false, null, 4),
  ('Villa Azalea Subdivision', 'Contractor (Glass Installation)', 'Cotcot, Liloan, Cebu', 'Completed', '2021', null, false, null, 5),
  ('Blanco Condo Renovation', 'General Contractor (All-in works)', 'One Oasis Cebu, Mabolo, Cebu City', 'Completed', '2021', null, false, null, 6),
  ('Benitez Condo Renovation', 'General Contractor (All-in works)', 'Horizons 101, General Maxilom Ave., Cebu City', 'Completed', '2022', null, false, null, 7),
  ('Dacles Residence', 'General Contractor (All-in works)', 'Sangat, San Fernando', 'Completed', '2021', 'House construction delivered as general contractor with full coordination of trades and site execution.', true, 'completed', 8),
  ('JStore Innovation Worldwide Corporation Warehouse', 'General Contractor (All-in works)', 'Canjulao, Lapu-Lapu City', 'Completed', '2019', null, false, null, 9),
  ('Saekyung Village Condominium Residences', 'Painting Contractor', 'Marigondon, Beach Road, Marigondon, Lapu-Lapu City', 'Completed', '2022', null, false, null, 10),
  ('Ehrlich IT Services Inc. Office', 'General Contractor (All-in works)', 'Cardoc Building, General Maxilom Ave., Cebu City', 'Completed', '2022', null, false, null, 11),
  ('Happy Tails Veterinary Clinic', 'General Contractor (All-in works)', 'Labangon Tower Center, Cebu City', 'Completed', '2022', null, false, null, 12),
  ('Two-storey Commercial Building', 'General Contractor (All-in works)', 'Brgy. Kasanta, Mactan, Lapu-Lapu City', 'Completed', '2023', null, false, null, 13),
  ('Two-storey Residential Building', 'General Contractor (All-in works)', 'Brgy. Agus, Basak, Lapu-Lapu City', 'Completed', '2023', null, false, null, 14),
  ('MLhuillier Outlet', 'General Contractor (All-in works)', 'Canduman, Mandaue City', 'Completed', '2024', null, false, null, 15),
  ('Beauty Blush Outlet', 'General Contractor (All-in works)', 'Canduman, Mandaue City', 'Completed', '2024', null, false, null, 16),
  ('Tajanlangit Condo Renovation', 'General Contractor (All-in works)', 'Bamboo Bay Residences, Hernan Cortes, Mandaue City', 'Completed', '2025', null, false, null, 17),
  ('Dr. Sanchez Residence', 'General Contractor (All-in works)', 'St. Martin Heights, Guadalupe, Cebu City', 'Completed', '2024', 'A high-end private residence designed and constructed with premium finishes and meticulous attention to detail. The project required careful coordination of architectural elements and specialized trades to achieve the desired quality standards and refined interior aesthetics.', true, 'completed', 18),
  ('Sps. Zabala Royal Ocean Crest Condominium Fit-out', 'General Contractor (All-in works)', 'Dauis, Bohol', 'Completed', '2025', null, false, null, 19),
  ('Caballero Residence', 'General Contractor (All-in works)', 'Corella, Bohol', 'Completed', 'Feb 2026', 'Steer Builders Corporation''s first project outside Cebu — a one-storey senior-friendly residence in Corella, Bohol with practical layouts, accessibility considerations, and mid-range finishes built for long-term comfort and safety.', true, 'completed', 20),
  ('Sunberry Homes 2 Subdivision', 'Contractor (Cabinetry Works)', 'Sudtonggan, Basak, Lapu-Lapu City', 'Ongoing', 'Ongoing', null, false, null, 21),
  ('Ashana Coast Residences', 'General Contractor (Labor only)', 'Catarman, Liloan, Cebu', 'Ongoing', 'Ongoing', 'A residential housing development of two-storey units. Under a labor-only engagement, SBC handles manpower deployment and on-site construction execution for structural and architectural works.', true, 'ongoing', 22),
  ('Sweetberries Community', 'General Contractor (Labor only)', 'Cambuhawe, Balamban, Cebu', 'Ongoing', 'Ongoing', 'An ongoing residential development of multiple one-storey townhouse units. SBC provides full manpower and site execution services covering structural, architectural, and finishing works.', true, 'ongoing', 23),
  ('Esteem Medica Clinic Renovation', 'General Contractor (All-in works)', 'Bamboo Bay Residences, Hernan Cortes, Mandaue City', 'Put on hold in 2025', 'Put on hold in 2025', null, false, null, 24),
  ('Leyva Residences Renovation Works', 'General Contractor (All-in works)', 'Tisa, Cebu City', 'Ongoing', 'Ongoing', null, false, null, 25),
  ('Sunberry Homes Augmentation Works', 'General Contractor (Labor only)', 'Brgy. Sudtunggan, Lapu-Lapu City, Cebu', 'Ongoing', 'Ongoing', null, false, null, 26),
  ('Casa Mira Homes Iloilo Augmentation Works', 'General Contractor', 'Brgy. Camalig, Jaro, Iloilo', 'Ongoing', 'Ongoing', 'Residential housing development with labor-only augmentation works — manpower deployment and on-site execution in accordance with project plans and timelines.', true, 'ongoing', 27),
  ('Velmiro Heights Cagayan de Oro Augmentation Works', 'General Contractor', 'Brgy. Agusan, Cagayan de Oro City', 'Ongoing', 'Ongoing', null, false, null, 28),
  ('Velmiro Heights Cagayan de Oro House Construction (4 units)', 'General Contractor (All-in works)', 'Brgy. Agusan, Cagayan de Oro City', 'Ongoing', 'Ongoing', null, false, null, 29);